services:
  api:
    environment:
      - NODE_ENV=development
      - DOMAIN_CLIENT=http://localhost
      - DOMAIN_SERVER=http://localhost
      - ALLOW_EMAIL_LOGIN=true
      - ALLOW_REGISTRATION=true
      - ALLOW_SOCIAL_LOGIN=false
      - OPENID_CLIENT_ID=
      - OPENID_CLIENT_SECRET=
      - OPENID_ISSUER=
      - OPENID_SESSION_SECRET=
      - OPENID_SCOPE=
      - OPENID_IMAGE_URL=
